on:
  pull_request: null
  push:
    branches:
      - master
    tags-ignore:
      - '**'
    paths-ignore:
      - '**/*.md'
      - LICENSE
      - '**/*.gitignore'
      - .editorconfig
      - docs/**
jobs:
  Linux:
    name: Test on Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 16, 18, 20]
    steps:
      - uses: actions/checkout@v3
        with:
          # 等同于 run: git submodule update --init --recursive
          submodules: recursive
      # On Mac, when Node.js v14 + Python v3.11, node-gyp compilation reports an error:
      # ValueError: invalid mode: 'rU' while trying to load binding.gyp
      # See https://github.com/iotaledger/wallet.rs/pull/1613
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Python verison
        run: python --version

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          check-latest: true
          cache: npm
      - name: Install dependencies
        run: npm install
      - name: Build bindings
        run: npm run build
      - name: Test bindings
        run: npm test

  macOS:
    name: Test on macOS
    runs-on: macos-latest
    strategy:
      matrix:
        node: [14, 16, 18, 20]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Python verison
        run: python --version

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          check-latest: true
          cache: npm
      - name: Install dependencies
        run: npm install
      - name: Build bindings
        run: npm run build
      - name: Test bindings
        run: npm test
